name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile"
      - ".github/workflows/hadolint.yml"
  pull_request:
    paths:
      - "**/Dockerfile"
      - ".github/workflows/hadolint.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    uses: peaceiris/workflows/.github/workflows/hadolint.yml@v0.20.1
