name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile"
      - ".github/workflows/hadolint.yml"
  pull_request:
    paths:
      - "**/Dockerfile"
      - ".github/workflows/hadolint.yml"

jobs:
  lint:
    uses: peaceiris/workflows/.github/workflows/hadolint.yml@v0.21.2
